### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by katsu9246** [katsu9246/furima-37990#22]
# URL
https://furima-37990.herokuapp.com/
# Basic認証のIDとパスワード
ID: katsu9246
PW: ao77211405
# 出品者用のメールアドレスとパスワード
E-mail: furima_gekikarataro@awstest.com
PW: furima12345
# 購入者用のメールアドレスとパスワード
E-mail: furima_amataro@awstest.com
PW: furima12345

**Comment by shodai-ito** [comment]
@katsu9246 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**`商品出品機能`**
- [x] **商品画像を1枚つけることが必須であること(ActiveStorageを使用すること)**
画像なしでも出品できてしまいます。

- [x] **エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
金額についてのエラーメッセージが重複しております。
<img width="268" alt="スクリーンショット 2022-07-25 14 41 56" src="https://user-images.githubusercontent.com/62537107/180706452-27f8bcc8-8ea2-4880-a484-6b78e0429b8b.png">

※画像なしの商品を出品して以降エラーとなり、動作確認ができていない為、次回ご提出時にそのほかの機能も併せて確認させていただきます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by katsu9246** [comment]
確認ありがとうございます。
商品出品機能について、不具合を確認しました。
当該不具合について修正が終わりましたので、引き続きご確認ください。
各種ID、PW、Emailは変更ありません。

**Comment by motomuun** [comment]
@katsu9246 さん、再度のご提出ありがとうございます‼︎
動作の確認をしたところ、一点だけ修正していただきたい箇所がございました。
それ以外の箇所に関しては問題なく動作確認が出来ております。
以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能の確認**

- [x] **ページ下部の「もどる」ボタンを押すと、編集途中の情報は破棄され、商品詳細表示ページに遷移すること**
「もどる」ボタンを押すと、商品詳細ページでなく、トップページに遷移されます。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by katsu9246** [comment]
確認ありがとうございます。
商品編集機能について、ご指摘の不具合を確認しました。
当該不具合について修正が終わりましたので、引き続きご確認ください。
各種ID、PW、Emailは変更ありません。
宜しくお願いします。

**Comment by snkw-works** [comment]
@katsu9246 さん、ご提出ありがとうございます‼︎
修正が確認でき、正常に動作することが確認できました！　**LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/164166779-9eca4a1e-955a-4d55-bfa3-c0ff25e73e87.png)

**Comment by katsu9246** [comment]
ありがとうございます！！
メンターの皆様の支え無くして実現できませんでした。
この場を借りて御礼申し上げます。
